dist: xenial
sudo: required
language: cpp

cache:
    directories:
        - $HOME/prereq
        - $HOME/local

script:
    - bash ci/install-packages.sh
    - bash ci/setup-prereq-ext.sh
    - bash ci/setup-prereq.sh
    - bash ci/setup-cowlang.sh
    - bash ci/unit-tests.sh
